/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.game {
    export class GameHomeViewUI extends Laya.Scene {
		public spNum:Laya.Sprite;
		public imageSpFull:Laya.Image;
		public imageBtAttSp:Laya.Image;
		public stLableTime:Laya.Label;
		public imageBtGoldAdd:Laya.Image;
		public glodNum:Laya.Sprite;
		public back_btn:Laya.Sprite;
		public imageBtStartGame:Laya.Image;
		public imageBtFreeSkin:Laya.Image;
		public imageFreeSkin:Laya.Image;
		public boxFun:Laya.Box;
		public imageBtShare:Laya.Image;
		public imageBtChoseLevel:Laya.Image;
		public imageBtSign:Laya.Image;
		public imageBtInvital:Laya.Image;
		public boxLevel:Laya.Box;
		public spLevelNum:Laya.Sprite;
		public btn_more:Laya.Sprite;
		public imageWeCatMoreGame:Laya.Image;
		public imageRed:Laya.Image;
		public more_games:Laya.Image;
		public btn_colorSign:Laya.Button;
		public btn_lottery:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GameHomeView");
        }
    }
    REG("ui.game.GameHomeViewUI",GameHomeViewUI);
    export class GameViewUI extends Laya.Scene {
		public boxBtList:Laya.Box;
		public imageBtGotoNextLevel:Laya.Image;
		public imageBtTip:Laya.Image;
		public imageBtRestart:Laya.Image;
		public imageBtToHome:Laya.Image;
		public boxLevelInfo:Laya.HBox;
		public spLevelLeft:Laya.Sprite;
		public hBoxIndex:Laya.HBox;
		public spLevelRight:Laya.Sprite;
		public box_choose:Laya.Box;
		public icon_chooseRight:Laya.Image;
		public icon_chooseLeft:Laya.Image;
		public icon_left:Laya.Image;
		public icon_right:Laya.Image;
		public imageHand:Laya.Image;
		public spNum:Laya.Sprite;
		public imageSpFull:Laya.Image;
		public imageBtAttSp:Laya.Image;
		public stLableTime:Laya.Label;
		public imageBtGoldAdd:Laya.Image;
		public glodNum:Laya.Sprite;
		public imageTTVideo:Laya.Image;
		public imageWeCatMoreGame:Laya.Image;
		public imageRed:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GameView");
        }
    }
    REG("ui.game.GameViewUI",GameViewUI);
    export class PopChooseSceneUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public box_choose:Laya.Box;
		public icon_chooseLeft:Laya.Image;
		public icon_chooseRight:Laya.Image;
		public icon_left:Laya.Image;
		public icon_right:Laya.Image;
		public boxBtList:Laya.Box;
		public imageBtGotoNextLevel:Laya.Image;
		public imageBtTip:Laya.Image;
		public imageBtRestart:Laya.Image;
		public imageBtToHome:Laya.Image;
		public hBoxIndex:Laya.HBox;
		public imageSpFull:Laya.Image;
		public imageBtAttSp:Laya.Image;
		public imageBtGoldAdd:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/PopChooseScene");
        }
    }
    REG("ui.game.PopChooseSceneUI",PopChooseSceneUI);
}
export module ui.game.level {
    export class LevelScene1UI extends Laya.Scene {
		public box_game:Laya.Box;
		public icon_bg:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene1");
        }
    }
    REG("ui.game.level.LevelScene1UI",LevelScene1UI);
    export class LevelScene10UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public box_game_up:Laya.Box;
		public box_enb:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene10");
        }
    }
    REG("ui.game.level.LevelScene10UI",LevelScene10UI);
    export class LevelScene11UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_game_up:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene11");
        }
    }
    REG("ui.game.level.LevelScene11UI",LevelScene11UI);
    export class LevelScene12UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene12");
        }
    }
    REG("ui.game.level.LevelScene12UI",LevelScene12UI);
    export class LevelScene13UI extends Laya.Scene {
		public bgM_box:Laya.Box;
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public xtBox:Laya.Box;
		public boxDialog:Laya.Box;
		public box_game_up:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene13");
        }
    }
    REG("ui.game.level.LevelScene13UI",LevelScene13UI);
    export class LevelScene14UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_g:Laya.Box;
		public box_z:Laya.Box;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene14");
        }
    }
    REG("ui.game.level.LevelScene14UI",LevelScene14UI);
    export class LevelScene15UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_enb1:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene15");
        }
    }
    REG("ui.game.level.LevelScene15UI",LevelScene15UI);
    export class LevelScene16UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_game_up:Laya.Box;
		public box_player:Laya.Box;
		public box_game_1:Laya.Box;
		public box_game_up_1:Laya.Box;
		public xtBox:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene16");
        }
    }
    REG("ui.game.level.LevelScene16UI",LevelScene16UI);
    export class LevelScene17UI extends Laya.Scene {
		public box_game:Laya.Box;
		public bgM_box:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene17");
        }
    }
    REG("ui.game.level.LevelScene17UI",LevelScene17UI);
    export class LevelScene18UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_dx:Laya.Box;
		public box_hp:Laya.Box;
		public box_sg:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene18");
        }
    }
    REG("ui.game.level.LevelScene18UI",LevelScene18UI);
    export class LevelScene19UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_dianti:Laya.Box;
		public box_dog:Laya.Box;
		public box_player:Laya.Box;
		public box_qiqiu:Laya.Box;
		public box_enb:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene19");
        }
    }
    REG("ui.game.level.LevelScene19UI",LevelScene19UI);
    export class LevelScene2UI extends Laya.Scene {
		public box_game:Laya.Box;
		public icon_bg:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene2");
        }
    }
    REG("ui.game.level.LevelScene2UI",LevelScene2UI);
    export class LevelScene20UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_enb2:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene20");
        }
    }
    REG("ui.game.level.LevelScene20UI",LevelScene20UI);
    export class LevelScene21UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_bg_top:Laya.Box;
		public box_brokenBridge:Laya.Box;
		public box_gopher:Laya.Box;
		public img_hole:Laya.Image;
		public box_iceHole:Laya.Box;
		public img_iceHole:Laya.Image;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
		public box_bg_bottom:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene21");
        }
    }
    REG("ui.game.level.LevelScene21UI",LevelScene21UI);
    export class LevelScene22UI extends Laya.Scene {
		public box_game:Laya.Box;
		public boxUp:Laya.Box;
		public box_xiong:Laya.Box;
		public box_xiong2:Laya.Box;
		public box_xueren:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene22");
        }
    }
    REG("ui.game.level.LevelScene22UI",LevelScene22UI);
    export class LevelScene23UI extends Laya.Scene {
		public box_game:Laya.Box;
		public icon_changjing:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_enb1:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene23");
        }
    }
    REG("ui.game.level.LevelScene23UI",LevelScene23UI);
    export class LevelScene24UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_yudi:Laya.Box;
		public box_xueren:Laya.Box;
		public box_huoba:Laya.Box;
		public box_player:Laya.Box;
		public box_laoshu:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene24");
        }
    }
    REG("ui.game.level.LevelScene24UI",LevelScene24UI);
    export class LevelScene25UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene25");
        }
    }
    REG("ui.game.level.LevelScene25UI",LevelScene25UI);
    export class LevelScene26UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene26");
        }
    }
    REG("ui.game.level.LevelScene26UI",LevelScene26UI);
    export class LevelScene27UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene27");
        }
    }
    REG("ui.game.level.LevelScene27UI",LevelScene27UI);
    export class LevelScene28UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_green:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene28");
        }
    }
    REG("ui.game.level.LevelScene28UI",LevelScene28UI);
    export class LevelScene29UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene29");
        }
    }
    REG("ui.game.level.LevelScene29UI",LevelScene29UI);
    export class LevelScene3UI extends Laya.Scene {
		public box_game:Laya.Box;
		public icon_bg:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene3");
        }
    }
    REG("ui.game.level.LevelScene3UI",LevelScene3UI);
    export class LevelScene30UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_huo:Laya.Box;
		public box_shitou:Laya.Box;
		public box_long:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene30");
        }
    }
    REG("ui.game.level.LevelScene30UI",LevelScene30UI);
    export class LevelScene31UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_rope:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene31");
        }
    }
    REG("ui.game.level.LevelScene31UI",LevelScene31UI);
    export class LevelScene32UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene32");
        }
    }
    REG("ui.game.level.LevelScene32UI",LevelScene32UI);
    export class LevelScene33UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
		public box_dog:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene33");
        }
    }
    REG("ui.game.level.LevelScene33UI",LevelScene33UI);
    export class LevelScene34UI extends Laya.Scene {
		public box_game:Laya.Box;
		public image_box:Laya.Sprite;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene34");
        }
    }
    REG("ui.game.level.LevelScene34UI",LevelScene34UI);
    export class LevelScene35UI extends Laya.Scene {
		public box_game:Laya.Box;
		public image_mask:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene35");
        }
    }
    REG("ui.game.level.LevelScene35UI",LevelScene35UI);
    export class LevelScene36UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene36");
        }
    }
    REG("ui.game.level.LevelScene36UI",LevelScene36UI);
    export class LevelScene37UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene37");
        }
    }
    REG("ui.game.level.LevelScene37UI",LevelScene37UI);
    export class LevelScene38UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_player:Laya.Box;
		public box_enb:Laya.Box;
		public imgMask:Laya.Image;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene38");
        }
    }
    REG("ui.game.level.LevelScene38UI",LevelScene38UI);
    export class LevelScene39UI extends Laya.Scene {
		public box_game:Laya.Box;
		public image_special:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene39");
        }
    }
    REG("ui.game.level.LevelScene39UI",LevelScene39UI);
    export class LevelScene4UI extends Laya.Scene {
		public box_game:Laya.Box;
		public icon_bg:Laya.Image;
		public box_enb:Laya.Box;
		public icon_tree:Laya.Image;
		public box_enb1:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene4");
        }
    }
    REG("ui.game.level.LevelScene4UI",LevelScene4UI);
    export class LevelScene40UI extends Laya.Scene {
		public box_game:Laya.Box;
		public imgFire:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene40");
        }
    }
    REG("ui.game.level.LevelScene40UI",LevelScene40UI);
    export class LevelScene5UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public icon_tree:Laya.Image;
		public box_enb1:Laya.Box;
		public box_player:Laya.Box;
		public box_enb2:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene5");
        }
    }
    REG("ui.game.level.LevelScene5UI",LevelScene5UI);
    export class LevelScene6UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enbhuo2:Laya.Box;
		public box_enbhuo3:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_enb1:Laya.Box;
		public box_enbyan2:Laya.Box;
		public box_enbyan3:Laya.Box;
		public box_enbyan4:Laya.Box;
		public box_Animatedscenes:Laya.Box;
		public imageBg:Laya.Image;
		public imageMot:Laya.Image;
		public imageShip:Laya.Image;
		public imageWaterBlue1:Laya.Image;
		public imageWaterBlue2:Laya.Image;
		public imageWaterBotton1:Laya.Image;
		public imageWaterBotton2:Laya.Image;
		public boxBg:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene6");
        }
    }
    REG("ui.game.level.LevelScene6UI",LevelScene6UI);
    export class LevelScene7UI extends Laya.Scene {
		public box_game:Laya.Box;
		public image3up:Laya.Image;
		public image2Temp:Laya.Image;
		public image2up:Laya.Image;
		public image2yun:Laya.Image;
		public image2yunTemp:Laya.Image;
		public imageSun:Laya.Image;
		public box_watorUp:Laya.Box;
		public boxWaterUp1:Laya.Box;
		public imageWaterUp1:Laya.Image;
		public imageWaterUp2:Laya.Image;
		public imageWaterUp1Temp:Laya.Image;
		public imageWaterUp2Temp:Laya.Image;
		public boxWaterUp2:Laya.Box;
		public imageWaterUp1After:Laya.Image;
		public imageWaterUp2After:Laya.Image;
		public imageWaterUp1AfterTemp:Laya.Image;
		public imageWaterUp2AfterTemp:Laya.Image;
		public box_fire:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public box_watorDown:Laya.Box;
		public boxWaterDown1:Laya.Box;
		public imageWaterDown1:Laya.Image;
		public imageWaterDown2:Laya.Image;
		public imageWaterDown1Temp:Laya.Image;
		public imageWaterDown2Temp:Laya.Image;
		public boxWaterDown2:Laya.Box;
		public imageWaterDown2After1:Laya.Image;
		public imageWaterDown2After2:Laya.Image;
		public imageWaterDown2After1Temp:Laya.Image;
		public imageWaterDown2After2Temp:Laya.Image;
		public box_enb1:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene7");
        }
    }
    REG("ui.game.level.LevelScene7UI",LevelScene7UI);
    export class LevelScene8UI extends Laya.Scene {
		public box_game:Laya.Box;
		public imageBg1:Laya.Image;
		public imageBg2:Laya.Image;
		public imageBg3:Laya.Image;
		public imageBg4:Laya.Image;
		public imageBg5:Laya.Image;
		public box_watorUp:Laya.Box;
		public boxWaterUp1:Laya.Box;
		public imageWaterUp1:Laya.Image;
		public imageWaterUp2:Laya.Image;
		public boxWaterUp2:Laya.Box;
		public imageWaterUp1After:Laya.Image;
		public imageWaterUp2After:Laya.Image;
		public box_watorDown:Laya.Box;
		public boxWaterDown1:Laya.Box;
		public imageWaterDown1:Laya.Image;
		public imageWaterDown2:Laya.Image;
		public boxWaterDown2:Laya.Box;
		public imageWaterDown2After1:Laya.Image;
		public imageWaterDown2After2:Laya.Image;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene8");
        }
    }
    REG("ui.game.level.LevelScene8UI",LevelScene8UI);
    export class LevelScene9UI extends Laya.Scene {
		public box_game:Laya.Box;
		public box_enb:Laya.Box;
		public box_player:Laya.Box;
		public boxDialog:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/LevelScene9");
        }
    }
    REG("ui.game.level.LevelScene9UI",LevelScene9UI);
    export class WeCatMoreGameItemOne1UI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/level/WeCatMoreGameItemOne1");
        }
    }
    REG("ui.game.level.WeCatMoreGameItemOne1UI",WeCatMoreGameItemOne1UI);
}
export module ui.game.uiView {
    export class AddSpViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public btLable:Laya.Sprite;
		public imageBtGet:Laya.Box;
		public spNum:Laya.Sprite;
		public box_qq:Laya.Box;
		public box_index:Laya.Box;
		public box_up:Laya.Box;
		public box_down:Laya.Box;
		public box_lable:Laya.Box;
		public lable_number:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/AddSpView");
        }
    }
    REG("ui.game.uiView.AddSpViewUI",AddSpViewUI);
    export class CommonViewUI extends Laya.Scene {
		public sp:Laya.Image;
		public spNum:Laya.Sprite;
		public imageSpFull:Laya.Image;
		public imageBtAttSp:Laya.Image;
		public stLableTime:Laya.Label;
		public imageBtGoldAdd:Laya.Image;
		public glodNum:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/CommonView");
        }
    }
    REG("ui.game.uiView.CommonViewUI",CommonViewUI);
    export class FailEntryOneViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public img_back:Laya.Image;
		public imageRecv:Laya.Box;
		public imageGoodsType:Laya.Image;
		public spGlod:Laya.Sprite;
		public imageBtSign:Laya.Box;
		public boxAni:Laya.Box;
		public box_wecat:Laya.Box;
		public btLable:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/FailEntryOneView");
        }
    }
    REG("ui.game.uiView.FailEntryOneViewUI",FailEntryOneViewUI);
    export class FailEntryTwoViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageWeCatMoreGame:Laya.Image;
		public panelWeCatMoreGame:Laya.Panel;
		public btLable:Laya.Image;
		public imageBtShare:Laya.Box;
		public imageShareIcon:Laya.Image;
		public imageShareName:Laya.Image;
		public ttGoodsType:Laya.Image;
		public ttSpecial:Laya.Sprite;
		public shareGlodCount:Laya.Sprite;
		public imageRecv:Laya.Box;
		public imageGoodsType:Laya.Image;
		public spCount:Laya.Sprite;
		public box_wecat:Laya.Box;
		public box_content:Laya.Box;
		public imageBtToHome:Laya.Image;
		public imageBtRestart:Laya.Box;
		public spCost:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/FailEntryTwoView");
        }
    }
    REG("ui.game.uiView.FailEntryTwoViewUI",FailEntryTwoViewUI);
    export class GuessLikeUI extends Laya.Scene {
		public panelList:Laya.Panel;
		public boxView:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/GuessLike");
        }
    }
    REG("ui.game.uiView.GuessLikeUI",GuessLikeUI);
    export class GuessLikeItemUI extends Laya.Scene {
		public icon_:Laya.Image;
		public iconMask_:Laya.Image;
		public name_txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/GuessLikeItem");
        }
    }
    REG("ui.game.uiView.GuessLikeItemUI",GuessLikeItemUI);
    export class InviteFriendsIndexViewUI extends Laya.Scene {
		public bg:Laya.Sprite;
		public img_index:Laya.Image;
		public img_null:Laya.Image;
		public img_head:Laya.Image;
		public img_award:Laya.Image;
		public img_no:Laya.Image;
		public img_get:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/InviteFriendsIndexView");
        }
    }
    REG("ui.game.uiView.InviteFriendsIndexViewUI",InviteFriendsIndexViewUI);
    export class InviteFriendsViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageBtInvite:Laya.Image;
		public panelInva:Laya.Panel;
		public boxInva:Laya.Box;
		public btn_close:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/InviteFriendsView");
        }
    }
    REG("ui.game.uiView.InviteFriendsViewUI",InviteFriendsViewUI);
    export class LevelIndexViewUI extends Laya.Scene {
		public spBg:Laya.Sprite;
		public levelNum:Laya.Sprite;
		public spG:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/LevelIndexView");
        }
    }
    REG("ui.game.uiView.LevelIndexViewUI",LevelIndexViewUI);
    export class LevelViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageBtHome:Laya.Image;
		public levelPanel:Laya.Panel;
		public levelBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/LevelView");
        }
    }
    REG("ui.game.uiView.LevelViewUI",LevelViewUI);
    export class MoreGameItemViewUI extends Laya.Scene {
		public goBtn:Laya.Button;
		public headiconImg:Laya.Image;
		public desLabel:Laya.Label;
		public titleLabel:Laya.Label;
		public baokuanImg:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameItemView");
        }
    }
    REG("ui.game.uiView.MoreGameItemViewUI",MoreGameItemViewUI);
    export class MoreGameOperReqIndexUI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
		public lableCount:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameOperReqIndex");
        }
    }
    REG("ui.game.uiView.MoreGameOperReqIndexUI",MoreGameOperReqIndexUI);
    export class MoreGameOperRequestUI extends Laya.Scene {
		public imageBtReturn:Laya.Image;
		public lableTitle:Laya.Label;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtConGame:Laya.Image;
		public imageRandom:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameOperRequest");
        }
    }
    REG("ui.game.uiView.MoreGameOperRequestUI",MoreGameOperRequestUI);
    export class MoreGameOperRequestTempUI extends Laya.Scene {
		public imageBtReturn:Laya.Image;
		public lableTitle:Laya.Label;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtConGame:Laya.Image;
		public imageRandom:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameOperRequestTemp");
        }
    }
    REG("ui.game.uiView.MoreGameOperRequestTempUI",MoreGameOperRequestTempUI);
    export class MoreGameOperRequestTwoUI extends Laya.Scene {
		public imageBtReturn:Laya.Image;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtConGame:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameOperRequestTwo");
        }
    }
    REG("ui.game.uiView.MoreGameOperRequestTwoUI",MoreGameOperRequestTwoUI);
    export class MoreGameViewUI extends Laya.Scene {
		public panel:Laya.Panel;
		public tLabel:Laya.Label;
		public image_back:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/MoreGameView");
        }
    }
    REG("ui.game.uiView.MoreGameViewUI",MoreGameViewUI);
    export class ShareRecordVideoSkinViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public shareGlodCount:Laya.Image;
		public btn_shareVideo:Laya.Button;
		public btn_cancel:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/ShareRecordVideoSkinView");
        }
    }
    REG("ui.game.uiView.ShareRecordVideoSkinViewUI",ShareRecordVideoSkinViewUI);
    export class SignViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageBtSign:Laya.Image;
		public spBtClose:Laya.Sprite;
		public boxDouble:Laya.Box;
		public btDouble:Laya.Sprite;
		public spDouble:Laya.Sprite;
		public boxItem:Laya.Box;
		public spWorldLeft:Laya.Sprite;
		public spWorldRight:Laya.Sprite;
		public spTomorrow:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SignView");
        }
    }
    REG("ui.game.uiView.SignViewUI",SignViewUI);
    export class SkinItemViewUI extends Laya.Scene {
		public imageBg:Laya.Image;
		public imageSkinReal:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SkinItemView");
        }
    }
    REG("ui.game.uiView.SkinItemViewUI",SkinItemViewUI);
    export class SkinViewUI extends Laya.Scene {
		public imageBtToHome:Laya.Image;
		public panelSkin:Laya.Panel;
		public boxSkins:Laya.HBox;
		public imageBtWatchViceo:Laya.Box;
		public imageShareIcon:Laya.Image;
		public imageShareName:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SkinView");
        }
    }
    REG("ui.game.uiView.SkinViewUI",SkinViewUI);
    export class SuccessfulEntryOneViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public spTimeDown:Laya.Sprite;
		public imageParValue:Laya.Image;
		public imageBt:Laya.Image;
		public imageHand:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SuccessfulEntryOneView");
        }
    }
    REG("ui.game.uiView.SuccessfulEntryOneViewUI",SuccessfulEntryOneViewUI);
    export class SuccessfulEntryOneViewTwoUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageBtSign:Laya.Box;
		public lableAwardInfo:Laya.Label;
		public btLable:Laya.Image;
		public imageWeCatMoreGame:Laya.Image;
		public panelWeCatMoreGame:Laya.Panel;
		public boxAni:Laya.Box;
		public img_back:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SuccessfulEntryOneViewTwo");
        }
    }
    REG("ui.game.uiView.SuccessfulEntryOneViewTwoUI",SuccessfulEntryOneViewTwoUI);
    export class SuccessfulEntryThreeViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public spGlodAdd:Laya.Sprite;
		public imageGoodsTypeUp:Laya.Image;
		public imageWeCatMoreGame:Laya.Image;
		public panelWeCatMoreGame:Laya.Panel;
		public btNextLevel:Laya.Image;
		public btLable:Laya.Image;
		public imageRecv:Laya.Box;
		public imageGoodsType:Laya.Image;
		public spCountAddMore:Laya.Sprite;
		public spCost:Laya.Sprite;
		public imageBtShare:Laya.Box;
		public imageShareIcon:Laya.Image;
		public imageShareGameName:Laya.Image;
		public ttGoodsType:Laya.Image;
		public ttSpecial:Laya.Sprite;
		public shareGlodCount:Laya.Sprite;
		public imageBtRestart:Laya.Box;
		public spCostPs:Laya.Sprite;
		public box_lable:Laya.Box;
		public btDouble:Laya.Sprite;
		public spDouble:Laya.Sprite;
		public lableDesc:Laya.Label;
		public box_wecat:Laya.Box;
		public box_content:Laya.Box;
		public imageBtToHome:Laya.Image;
		public box_nextLevel:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SuccessfulEntryThreeView");
        }
    }
    REG("ui.game.uiView.SuccessfulEntryThreeViewUI",SuccessfulEntryThreeViewUI);
    export class SuccessfulEntryTwoViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public imageValue:Laya.Image;
		public imageBtSign:Laya.Image;
		public btLable:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/SuccessfulEntryTwoView");
        }
    }
    REG("ui.game.uiView.SuccessfulEntryTwoViewUI",SuccessfulEntryTwoViewUI);
    export class VentonesangerViewUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public image_change:Laya.Image;
		public imageValue:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/VentonesangerView");
        }
    }
    REG("ui.game.uiView.VentonesangerViewUI",VentonesangerViewUI);
    export class WeCatMoreGameItemOne713UI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatMoreGameItemOne713");
        }
    }
    REG("ui.game.uiView.WeCatMoreGameItemOne713UI",WeCatMoreGameItemOne713UI);
    export class WeCatMoreGameItemOne713BigUI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatMoreGameItemOne713Big");
        }
    }
    REG("ui.game.uiView.WeCatMoreGameItemOne713BigUI",WeCatMoreGameItemOne713BigUI);
    export class WeCatMoreGameItemTwoUI extends Laya.Scene {
		public imageIcon:Laya.Image;
		public lableGameName:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatMoreGameItemTwo");
        }
    }
    REG("ui.game.uiView.WeCatMoreGameItemTwoUI",WeCatMoreGameItemTwoUI);
    export class WeCatMoreGameViewUI extends Laya.Scene {
		public boxWeCatMoreGame:Laya.Box;
		public imageBg:Laya.Image;
		public panel_gamelist:Laya.Panel;
		public moreGamePanel:Laya.Box;
		public moreGamePanel2:Laya.Box;
		public imageBtWeCat:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatMoreGameView");
        }
    }
    REG("ui.game.uiView.WeCatMoreGameViewUI",WeCatMoreGameViewUI);
    export class WeCatOperReqItem713UI extends Laya.Scene {
		public image_icon:Laya.Image;
		public lable_name:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/WeCatOperReqItem713");
        }
    }
    REG("ui.game.uiView.WeCatOperReqItem713UI",WeCatOperReqItem713UI);
}
export module ui.game.uiView.lottery {
    export class LotterPopSceneUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public icon_title:Laya.Image;
		public box_count:Laya.Image;
		public btn_rfeceive:Laya.Image;
		public omg_r_video:Laya.Image;
		public btn_double:Laya.Image;
		public box_double:Laya.Box;
		public img_double:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/lottery/LotterPopScene");
        }
    }
    REG("ui.game.uiView.lottery.LotterPopSceneUI",LotterPopSceneUI);
    export class LotterySceneUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public img_lottery:Laya.Image;
		public btn_lottery:Laya.Button;
		public img_video:Laya.Image;
		public btn_close:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/lottery/LotteryScene");
        }
    }
    REG("ui.game.uiView.lottery.LotterySceneUI",LotterySceneUI);
    export class LotterySelSceneUI extends Laya.Scene {
		public img_lottery:Laya.Image;
		public btn_lottery:Laya.Button;
		public img_video:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/uiView/lottery/LotterySelScene");
        }
    }
    REG("ui.game.uiView.lottery.LotterySelSceneUI",LotterySelSceneUI);
}
export module ui.skins {
    export class HorizontalSkinViewUI extends Laya.Scene {
		public bg_img:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("skins/HorizontalSkinView");
        }
    }
    REG("ui.skins.HorizontalSkinViewUI",HorizontalSkinViewUI);
    export class VerticalSkinViewUI extends Laya.Scene {
		public bg_img:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("skins/VerticalSkinView");
        }
    }
    REG("ui.skins.VerticalSkinViewUI",VerticalSkinViewUI);
}
export module ui.skins.uiView.platfrom {
    export class PopVideoSceneUI extends Laya.Scene {
		public grp_center:Laya.Box;
		public btn_sure:Laya.Button;
		public btn_refuse:Laya.Button;
		public txt_desc:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("skins/uiView/platfrom/PopVideoScene");
        }
    }
    REG("ui.skins.uiView.platfrom.PopVideoSceneUI",PopVideoSceneUI);
}